package hansanhha.querydsl.book.util;

import hansanhha.querydsl.book.dto.CreateBookRequest;
import hansanhha.querydsl.book.vo.BookSubCategory;

import java.util.List;
import java.util.stream.Stream;

public record BookRequestFactory() {

    public static List<CreateBookRequest> getKoreanNovels() {
        String hanKang = "한강";
        String pakKyongni  = "박경리";
        BookSubCategory koreanLiterature = BookSubCategory.KOREAN_NOVEL;

        return List.of(
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("채식주의자", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("소년이 온다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("작별하지 않는다", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("희랍어 시간", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("아기부처", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("내 여자의 열매", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("여수의 사랑", hanKang, koreanLiterature),
                new CreateBookRequest("우리들의 일그러진 영웅", "이문열", koreanLiterature),
                new CreateBookRequest("토지 1권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 1권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 1권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 1권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 1권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 2권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 2권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 2권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 2권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 2권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 2권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 3권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 3권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 3권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 3권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 3권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 4권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 4권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 4권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 4권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 4권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 5권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 5권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 5권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 5권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 5권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 6권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 6권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 6권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 6권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 6권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 7권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 7권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 7권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 7권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 8권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 8권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 8권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 8권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 8권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 9권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 9권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 9권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 9권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 9권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 10권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 10권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 10권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 10권", pakKyongni, koreanLiterature),
                new CreateBookRequest("토지 10권", pakKyongni, koreanLiterature),
                new CreateBookRequest("시장과 전장", pakKyongni, koreanLiterature),
                new CreateBookRequest("시장과 전장", pakKyongni, koreanLiterature),
                new CreateBookRequest("시장과 전장", pakKyongni, koreanLiterature),
                new CreateBookRequest("시장과 전장", pakKyongni, koreanLiterature)
        );
    }

    public static List<CreateBookRequest> getProgrammings() {
        BookSubCategory programmingProgramData = BookSubCategory.PROGRAMMING_PROGRAM_DATA;
        BookSubCategory computerScience = BookSubCategory.COMPUTER_SCIENCE;

        return List.of(
                new CreateBookRequest("클린 코드", "로버트 C. 마틴", programmingProgramData),
                new CreateBookRequest("클린 코드", "로버트 C. 마틴", programmingProgramData),
                new CreateBookRequest("클린 코드", "로버트 C. 마틴", programmingProgramData),
                new CreateBookRequest("클린 코드", "로버트 C. 마틴", programmingProgramData),
                new CreateBookRequest("클린 코드", "로버트 C. 마틴", programmingProgramData),
                new CreateBookRequest("실용주의 프로그래머", "데이브토머스", programmingProgramData),
                new CreateBookRequest("실용주의 프로그래머", "데이브토머스", programmingProgramData),
                new CreateBookRequest("실용주의 프로그래머", "데이브토머스", programmingProgramData),
                new CreateBookRequest("실용주의 프로그래머", "데이브토머스", programmingProgramData),
                new CreateBookRequest("실용주의 프로그래머", "데이브토머스", programmingProgramData),
                new CreateBookRequest("생각하는 프로그래밍", "존벤틀리", programmingProgramData),
                new CreateBookRequest("생각하는 프로그래밍", "존벤틀리", programmingProgramData),
                new CreateBookRequest("생각하는 프로그래밍", "존벤틀리", programmingProgramData),
                new CreateBookRequest("생각하는 프로그래밍", "존벤틀리", programmingProgramData),
                new CreateBookRequest("생각하는 프로그래밍", "존벤틀리", programmingProgramData),
                new CreateBookRequest("테스트 주도 개발", "켄트 벡", programmingProgramData),
                new CreateBookRequest("테스트 주도 개발", "켄트 벡", programmingProgramData),
                new CreateBookRequest("테스트 주도 개발", "켄트 벡", programmingProgramData),
                new CreateBookRequest("테스트 주도 개발", "켄트 벡", programmingProgramData),
                new CreateBookRequest("테스트 주도 개발", "켄트 벡", programmingProgramData),
                new CreateBookRequest("Effective C", "로버트 C. 시코드", programmingProgramData),
                new CreateBookRequest("Effective C", "로버트 C. 시코드", programmingProgramData),
                new CreateBookRequest("Effective C", "로버트 C. 시코드", programmingProgramData),
                new CreateBookRequest("Effective C", "로버트 C. 시코드", programmingProgramData),
                new CreateBookRequest("Effective C", "로버트 C. 시코드", programmingProgramData),
                new CreateBookRequest("Effective C", "로버트 C. 시코드", programmingProgramData),
                new CreateBookRequest("Effective C", "로버트 C. 시코드", programmingProgramData),
                new CreateBookRequest("Effective C", "로버트 C. 시코드", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("기본기가 탄탄한 자바 개발자", "제이슨클라크", programmingProgramData),
                new CreateBookRequest("헤드 퍼스트 디자인 패턴", "캐시 시에라", programmingProgramData),
                new CreateBookRequest("헤드 퍼스트 디자인 패턴", "캐시 시에라", programmingProgramData),
                new CreateBookRequest("헤드 퍼스트 디자인 패턴", "캐시 시에라", programmingProgramData),
                new CreateBookRequest("헤드 퍼스트 디자인 패턴", "캐시 시에라", programmingProgramData),
                new CreateBookRequest("헤드 퍼스트 디자인 패턴", "캐시 시에라", programmingProgramData),
                new CreateBookRequest("헤드 퍼스트 디자인 패턴", "캐시 시에라", programmingProgramData),
                new CreateBookRequest("헤드 퍼스트 디자인 패턴", "캐시 시에라", programmingProgramData),
                new CreateBookRequest("헤드 퍼스트 디자인 패턴", "캐시 시에라", programmingProgramData),
                new CreateBookRequest("헤드 퍼스트 디자인 패턴", "캐시 시에라", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("자바 ORM 표준 JPA 프로그래밍", "김영한", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("모던 자바 인 액션", "라울-게이브리얼우르마", programmingProgramData),
                new CreateBookRequest("자바로 배우는 핵심 자료구조와 알고리즘", "앨런 B. 다우니", computerScience),
                new CreateBookRequest("자바로 배우는 핵심 자료구조와 알고리즘", "앨런 B. 다우니", computerScience),
                new CreateBookRequest("자바로 배우는 핵심 자료구조와 알고리즘", "앨런 B. 다우니", computerScience),
                new CreateBookRequest("자바로 배우는 핵심 자료구조와 알고리즘", "앨런 B. 다우니", computerScience),
                new CreateBookRequest("자바로 배우는 핵심 자료구조와 알고리즘", "앨런 B. 다우니", computerScience),
                new CreateBookRequest("쉽게 배우는 자료구조 with 자바", "문병로", computerScience),
                new CreateBookRequest("쉽게 배우는 자료구조 with 자바", "문병로", computerScience),
                new CreateBookRequest("쉽게 배우는 자료구조 with 자바", "문병로", computerScience),
                new CreateBookRequest("쉽게 배우는 자료구조 with 자바", "문병로", computerScience),
                new CreateBookRequest("쉽게 배우는 자료구조 with 자바", "문병로", computerScience),
                new CreateBookRequest("쉽게 배우는 자료구조 with 자바", "문병로", computerScience),
                new CreateBookRequest("코딩 테스트 합격자 되기 - 자바 편", "김희성", computerScience),
                new CreateBookRequest("코딩 테스트 합격자 되기 - 자바 편", "김희성", computerScience),
                new CreateBookRequest("코딩 테스트 합격자 되기 - 자바 편", "김희성", computerScience),
                new CreateBookRequest("코딩 테스트 합격자 되기 - 자바 편", "김희성", computerScience),
                new CreateBookRequest("코딩 테스트 합격자 되기 - 자바 편", "김희성", computerScience),
                new CreateBookRequest("자료구조와 알고리즘을 함께 Java!", "손상우", computerScience),
                new CreateBookRequest("자료구조와 알고리즘을 함께 Java!", "손상우", computerScience),
                new CreateBookRequest("자료구조와 알고리즘을 함께 Java!", "손상우", computerScience),
                new CreateBookRequest("자료구조와 알고리즘을 함께 Java!", "손상우", computerScience),
                new CreateBookRequest("자료구조와 알고리즘을 함께 Java!", "손상우", computerScience),
                new CreateBookRequest("자료구조와 알고리즘을 함께 Java!", "손상우", computerScience),
                new CreateBookRequest("자료구조와 알고리즘을 함께 Java!", "손상우", computerScience),
                new CreateBookRequest("Java 프로그래머를 위한 알고리즘과 자료구조", "Yoshiki Kondu", computerScience),
                new CreateBookRequest("Java 프로그래머를 위한 알고리즘과 자료구조", "Yoshiki Kondu", computerScience),
                new CreateBookRequest("Java 프로그래머를 위한 알고리즘과 자료구조", "Yoshiki Kondu", computerScience),
                new CreateBookRequest("Java 프로그래머를 위한 알고리즘과 자료구조", "Yoshiki Kondu", computerScience),
                new CreateBookRequest("Java 프로그래머를 위한 알고리즘과 자료구조", "Yoshiki Kondu", computerScience),
                new CreateBookRequest("Java 프로그래머를 위한 알고리즘과 자료구조", "Yoshiki Kondu", computerScience)
        );
    }

    public static List<CreateBookRequest> getAll() {
        return Stream.concat(getKoreanNovels().stream(), getProgrammings().stream()).toList();
    }
}
